export const ACTION_SET_SOLUTION = "SET_SOLUTION";
export const ACTION_SET_SCREEN = "SET_SCREEN";
export const ACTION_SET_SCREEN_VALUE = "SET_SCREEN_VALUE";
export const ACTION_SET_CONFIGURATION_VALUE = "SET_CONFIGURATION_VALUE";
